### PR TITLE
added numpy 1.18.1

### PR DESCRIPTION
**Pull request by faisal3325**

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
I don't think we should install numpy by default, but I'll modify the image to be able to install additional  dependencies

**Comment by faisal3325** [comment]
> I don't think we should install numpy by default, but I'll modify the image to be able to install additional dependencies

Hi @NielsZeilemaker, thanks for the acknowledgement. pyspark, uses numpy as it's dependencies. I had trouble running up a plain pyspark without any external library (numpy).

**Comment by NielsZeilemaker** [comment]
PySpark ML has a dependency on numpy, not PySpark itself. I'll have a look if I can create an option to allow you to install the extras

**Comment by NielsZeilemaker** [comment]
I've created #7 to support this, I'll close this PR. Let's continue to discuss on the other PR

**Pull request closed without merging**
